# Generated by Django 4.2.10 on 2026-03-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = []
