# Generated by Django 4.2.10 on 2026-03-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_collection_featured_product_customer_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
